add ex 3_1
icanwalkinyourmind/made_algo_2019 pull request #1
Opened 2019-11-04 10:15 UTC by icanwalkinyourmind

2019-11-08 22:19 UTC, ylyubimov requested changes
Дополнительно пришли сюда комментов ссылку на контест + Имя Фамилию Группу

2019-11-08 22:19 UTC, ylyubimov commented on ex_3_1/main.cpp
> +void merge_sort(int *arr, int n, int k) {
Давай сортировки сделаем шаблонными. И с произвольным класс-компаратором

2019-11-09 09:55 UTC, icanwalkinyourmind commented
https://contest.yandex.ru/contest/14768/run-report/23850194/

2019-11-13 21:46 UTC, ylyubimov approved these changes

2019-11-18 22:53 UTC, merged