add ex 4_3
icanwalkinyourmind/made_algo_2019 pull request #2
Opened 2019-11-04 10:15 UTC by icanwalkinyourmind

2019-11-08 22:21 UTC, ylyubimov requested changes
Ссылка на контест
Фамилия Имя Группа

2019-11-08 22:21 UTC, ylyubimov commented on ex_4_3/main.cpp
> +  while (pivot_place != k) {
Вынеси решение поиска статистики в отдельную функцию
Плюс тут также предполагалось искать статистику в любых данных, т.е. функция должна быть шаблонной и принимать произвольный класс-компаратор для сортировок.
Меня ревьювером перепрезови

2019-11-09 09:39 UTC, icanwalkinyourmind commented
https://contest.yandex.ru/contest/14768/run-report/23849366/

2019-11-13 21:48 UTC, ylyubimov approved these changes

2019-11-18 22:53 UTC, merged