add ex_7_3 impl
icanwalkinyourmind/made_algo_2019 pull request #3
Opened 2019-11-18 22:54 UTC by icanwalkinyourmind

https://contest.yandex.ru/contest/15368/run-report/25968263/

2019-11-22 00:03 UTC, ylyubimov requested changes

2019-11-22 00:03 UTC, ylyubimov commented on ex_7_3/main.cpp
> +  T get_k_stat(int k);
const

2019-11-22 00:03 UTC, ylyubimov commented on ex_7_3/main.cpp
> +  ~Treap();
правило пяти

2019-11-22 00:03 UTC, ylyubimov commented on ex_7_3/main.cpp
> +  void pre_order(std::function<void(TreapNode<T> *)> action);
Зачем эта функция?

2019-11-22 00:03 UTC, ylyubimov commented on ex_7_3/main.cpp
> +  int get_subtree_size(TreapNode<T> *node);
static
split/merge - тоже

2019-11-22 00:03 UTC, ylyubimov commented on ex_7_3/main.cpp
> +  auto *dq = new std::deque<TreapNode<T> *>;
Опять, кажется, очередь не нужна. Достаточно указателя на узел.

2019-11-22 00:03 UTC, ylyubimov commented on ex_7_3/main.cpp
> +  pre_order([](TreapNode<T> *node) {
Здесь можно и рекурсивно бахнуть. Treap считается сбалансированным, и глубокой рекурсии не будет.

2019-11-24 09:43 UTC, icanwalkinyourmind commented on ex_7_3/main.cpp
> +  void pre_order(std::function<void(TreapNode<T> *)> action);
использовал в деструкторе,больше не нужна

2019-11-26 08:00 UTC, icanwalkinyourmind commented on ex_7_3/main.cpp
> +  T get_k_stat(int k);
done

2019-11-26 08:00 UTC, icanwalkinyourmind commented on ex_7_3/main.cpp
> +  ~Treap();
done

2019-11-26 08:00 UTC, icanwalkinyourmind commented on ex_7_3/main.cpp
> +  int get_subtree_size(TreapNode<T> *node);
done

2019-11-26 08:00 UTC, icanwalkinyourmind commented on ex_7_3/main.cpp
> +  auto *dq = new std::deque<TreapNode<T> *>;
done

2019-11-26 08:00 UTC, icanwalkinyourmind commented on ex_7_3/main.cpp
> +  pre_order([](TreapNode<T> *node) {
done

2019-12-03 06:36 UTC, ylyubimov approved these changes

2019-12-03 09:22 UTC, merged