ex 6_1 impl
icanwalkinyourmind/made_algo_2019 pull request #4
Opened 2019-11-18 22:55 UTC by icanwalkinyourmind

https://contest.yandex.ru/contest/15368/run-report/25967992/

2019-11-21 23:57 UTC, ylyubimov requested changes

2019-11-21 23:57 UTC, ylyubimov commented on ex_6_1/main.cpp
> +  ~SimpleTree();
Правило 5ти

2019-11-21 23:57 UTC, ylyubimov commented on ex_6_1/main.cpp
> +  while (!q->empty()) {
Зачем тебе очередь, если в ней не больше одного элемента?

2019-11-21 23:57 UTC, ylyubimov commented on ex_6_1/main.cpp
> +  auto *q = new std::queue<Node<T> *>;
очередь уж точно не по new выделять.
Просто std::queue<Node<T>*> q;

2019-11-26 08:00 UTC, icanwalkinyourmind commented on ex_6_1/main.cpp
> +  ~SimpleTree();
done

2019-11-26 08:00 UTC, icanwalkinyourmind commented on ex_6_1/main.cpp
> +  while (!q->empty()) {
done

2019-11-26 08:00 UTC, icanwalkinyourmind commented on ex_6_1/main.cpp
> +  auto *q = new std::queue<Node<T> *>;
done

2019-12-03 06:35 UTC, ylyubimov approved these changes
ок

2019-12-03 09:22 UTC, merged