ex 8_1 initial commit
icanwalkinyourmind/made_algo_2019 pull request #5
Opened 2019-11-24 11:24 UTC by icanwalkinyourmind

https://contest.yandex.ru/contest/15766/run-report/26872523/
Медведев Владислав MADE12

2019-11-27 22:18 UTC, ylyubimov approved these changes

2019-11-27 22:18 UTC, ylyubimov commented on ex_8_1/main.cpp
> +  bool contains(T key);
const

2019-11-27 22:18 UTC, ylyubimov commented on ex_8_1/main.cpp
> +struct Node {
Узел должен быть скрыт внутри хеш-таблицы

2019-11-27 22:19 UTC, ylyubimov requested changes

2019-11-27 22:19 UTC, ylyubimov commented on ex_8_1/main.cpp
> +    table[index] = new Node<T>(key);
При такой вставке могут появится дубликаты!!!

2019-11-28 08:33 UTC, icanwalkinyourmind commented on ex_8_1/main.cpp
> +  bool contains(T key);
done

2019-11-28 08:33 UTC, icanwalkinyourmind commented on ex_8_1/main.cpp
> +struct Node {
done

2019-11-28 08:33 UTC, icanwalkinyourmind commented on ex_8_1/main.cpp
> +    table[index] = new Node<T>(key);
done

2019-12-04 22:53 UTC, ylyubimov commented on ex_8_1/main.cpp
> +    table[index] = new Node<T>(key);
Да, ты прав дубликата не будет, но
get_key_position не годится, потому что вставка должна идти в первый возможный delete), чтобы потом не скипать много delete'ов

2019-12-04 22:54 UTC, ylyubimov requested changes

2019-12-04 22:54 UTC, ylyubimov commented on ex_8_1/main.cpp
> +    ++table_capacity;
И, кстати, только заметил, что вот это значение только растет, поэтому можно добавляя/удаляя одно значение раздуть таблицу до бесконечности!

2019-12-08 13:20 UTC, icanwalkinyourmind commented on ex_8_1/main.cpp
> +    ++table_capacity;
done

2019-12-08 13:20 UTC, icanwalkinyourmind commented on ex_8_1/main.cpp
> +    table[index] = new Node<T>(key);
done

2019-12-11 06:15 UTC, ylyubimov requested changes

2019-12-11 06:15 UTC, ylyubimov commented on ex_8_1/main.cpp
> +    --table_capacity;
Обрати внимание, что много deleted (все) также приводят к деградации таблицы. Поэтому их бы чистить

2019-12-11 06:15 UTC, ylyubimov commented on ex_8_1/main.cpp
> +    table[key_position] = new Node(key);
Давай уберем аллокации.
Извини, что сразу не написал, но аллокации убивают идею хеш-таблицы с открытой адресацией.
В этом случае лучше использовать метод цепочек.
Т.е. надо хранить не таблицу с указателями, а просто таблицу элементов

2019-12-11 06:15 UTC, ylyubimov commented on ex_8_1/main.cpp
> +  if (table[key_position] == nullptr) {
Вот тут все равно вставка прямо в пустой элемент, а не в удаленный.
Удаленный необязательно должен иметь тот же ключ, что и оригинальный.

2019-12-18 12:38 UTC, icanwalkinyourmind commented on ex_8_1/main.cpp
> +    --table_capacity;
done

2019-12-18 12:38 UTC, icanwalkinyourmind commented on ex_8_1/main.cpp
> +    table[key_position] = new Node(key);
done

2019-12-18 12:39 UTC, icanwalkinyourmind commented on ex_8_1/main.cpp
> +  if (table[key_position] == nullptr) {
done

2019-12-29 20:53 UTC, ylyubimov approved these changes

2019-12-30 08:40 UTC, merged