ex_9: complete task
icanwalkinyourmind/made_algo_2019 pull request #6
Opened 2019-12-09 18:50 UTC by icanwalkinyourmind

https://contest.yandex.ru/contest/15964/run-report/28724813/

2019-12-12 05:49 UTC, ylyubimov requested changes

2019-12-12 05:49 UTC, ylyubimov commented on ex_9/haffman.cpp
> +  auto codes_map = new std::map<byte, std::vector<bool>>;
не стоит стандартные контейнеры по new аллоцировать. Они ничего не весят, их можно создать на стеке

2019-12-12 05:49 UTC, ylyubimov commented on ex_9/haffman.cpp
> +    pq.push(new Node(it->first, it->second, false));
Нигде нет удаления узлов.

2019-12-12 05:49 UTC, ylyubimov commented on ex_9/haffman.cpp
> +    pq.push(new Node(it->first, it->second, false));
-1 балл по "минимальным требованиям"

2019-12-18 10:49 UTC, icanwalkinyourmind commented on ex_9/haffman.cpp
> +    pq.push(new Node(it->first, it->second, false));
done

2019-12-18 10:49 UTC, icanwalkinyourmind commented on ex_9/haffman.cpp
> +  auto codes_map = new std::map<byte, std::vector<bool>>;
done

2019-12-29 20:52 UTC, ylyubimov approved these changes

2019-12-30 08:40 UTC, merged